from pydantic import BaseModel


class BLOBChunk(BaseModel):
    # URI of the chunk.
    # S3 URI if the data is stored in S3.
    # Starts with "file://"" prefix if the data is stored on a local file system.
    uri: str
    # Actual size of chunk data if the BLOB has data.
    # Requested chunk size if the BLOB has no data yet (can be used for data upload).
    size: int
    # None if the BLOB has data.
    # ETag of the chunk data (generated by BLOB store) if the BLOB chunk was used to upload data.
    etag: str | None


class BLOB(BaseModel):
    # ID of the BLOB
    id: str
    # Ordered chunks of the BLOB if the BLOB has data.
    # Ordered chunks of the BLOB that can be used to upload data if the BLOB has no data yet.
    chunks: list[BLOBChunk]
