"""Tensorlake Sandbox SDK - Client for managing and interacting with sandboxes."""

from .async_client import AsyncSandboxClient
from .async_sandbox import AsyncSandbox
from .client import SandboxClient
from .desktop import Desktop
from .exceptions import (
    PoolInUseError,
    PoolNotFoundError,
    RemoteAPIError,
    SandboxConnectionError,
    SandboxError,
    SandboxException,
    SandboxNotFoundError,
    SandboxNotRoutableError,
    SandboxPending,
    SandboxResizeError,
)
from .file_system import (
    create_file_system,
    delete_file_system,
    list_file_systems,
)
from .models import (
    CLEAR_NETWORK_POLICY,
    TERMINATION_REASON_CANCELLED,
    TERMINATION_REASON_NO_CAPACITY,
    ArchivedSandboxInfo,
    AsyncPendingSandbox,
    CheckpointType,
    ClearNetworkPolicy,
    CommandExitReason,
    CommandResult,
    ContainerResourcesInfo,
    CopiedSandboxResponse,
    CopySandboxResponse,
    CreateSandboxPoolResponse,
    CreateSandboxResponse,
    CreateSnapshotResponse,
    DaemonInfo,
    DirectoryEntry,
    FileSystem,
    FileSystemMount,
    GetOrCreateOutcome,
    GpuAllocation,
    GpuModel,
    GpuRequest,
    GPUResources,
    HealthResponse,
    ListArchivedSandboxesResponse,
    ListDirectoryResponse,
    ManagedProcessExit,
    ManagedProcessHealthStatus,
    ManagedProcessInfo,
    ManagedProcessStatus,
    NetworkConfig,
    OutputEvent,
    OutputMode,
    OutputResponse,
    PendingSandbox,
    PoolContainerInfo,
    ProcessHealthCheck,
    ProcessHealthCheckType,
    ProcessInfo,
    ProcessStatus,
    ProcessUser,
    ProcessUserSpec,
    ResizeErrorReason,
    ResizeSandboxResources,
    ResizeStatus,
    RestartPolicy,
    RestartPolicyConfig,
    SandboxInfo,
    SandboxLogLevel,
    SandboxLogSignal,
    SandboxLogsResponse,
    SandboxPendingReason,
    SandboxPoolInfo,
    SandboxPortAccess,
    SandboxProcessLogFilter,
    SandboxProcessLogFiltersResponse,
    SandboxResourceResizeInfo,
    SandboxStatus,
    SendSignalResponse,
    SnapshotInfo,
    SnapshotStatus,
    SnapshotType,
    SnapshotWaitCondition,
    StdinMode,
    sandbox_url_from_ingress_endpoint,
)
from .pty import AsyncPty, Pty
from .sandbox import Sandbox
from .tunnel import AsyncTcpTunnel, TcpTunnel, TunnelAddress

__all__ = [
    # Lifecycle management
    "SandboxClient",
    "AsyncSandboxClient",
    # Sandbox interaction
    "Sandbox",
    "AsyncSandbox",
    "Pty",
    "AsyncPty",
    "Desktop",
    "TcpTunnel",
    "AsyncTcpTunnel",
    "TunnelAddress",
    # Lifecycle models
    "SandboxStatus",
    "SandboxPendingReason",
    "GetOrCreateOutcome",
    "SandboxInfo",
    "ResizeStatus",
    "ResizeErrorReason",
    "SandboxResourceResizeInfo",
    "ResizeSandboxResources",
    # Wait-free create and polling readiness (ADR 0086)
    "PendingSandbox",
    "AsyncPendingSandbox",
    "TERMINATION_REASON_NO_CAPACITY",
    "TERMINATION_REASON_CANCELLED",
    "SandboxPortAccess",
    "CreateSandboxResponse",
    "CopiedSandboxResponse",
    "CopySandboxResponse",
    "SandboxPoolInfo",
    "PoolContainerInfo",
    "CreateSandboxPoolResponse",
    "ContainerResourcesInfo",
    "GPUResources",
    "GpuAllocation",
    "GpuModel",
    "GpuRequest",
    "CLEAR_NETWORK_POLICY",
    "ClearNetworkPolicy",
    "NetworkConfig",
    "ArchivedSandboxInfo",
    "ListArchivedSandboxesResponse",
    "sandbox_url_from_ingress_endpoint",
    # File system management
    "FileSystem",
    "FileSystemMount",
    "create_file_system",
    "list_file_systems",
    "delete_file_system",
    # Snapshot models
    "SnapshotStatus",
    "SnapshotType",
    "SnapshotWaitCondition",
    "SnapshotInfo",
    "CheckpointType",
    "CreateSnapshotResponse",
    # Command result
    "CommandExitReason",
    "CommandResult",
    # Process models
    "ProcessStatus",
    "RestartPolicy",
    "RestartPolicyConfig",
    "ProcessHealthCheckType",
    "ProcessHealthCheck",
    "ManagedProcessStatus",
    "ManagedProcessHealthStatus",
    "ManagedProcessExit",
    "ManagedProcessInfo",
    "ProcessInfo",
    "SandboxLogLevel",
    "SandboxLogSignal",
    "SandboxLogsResponse",
    "SandboxProcessLogFilter",
    "SandboxProcessLogFiltersResponse",
    "StdinMode",
    "OutputMode",
    "ProcessUser",
    "ProcessUserSpec",
    "SendSignalResponse",
    "OutputResponse",
    "OutputEvent",
    # File models
    "DirectoryEntry",
    "ListDirectoryResponse",
    # Daemon models
    "DaemonInfo",
    "HealthResponse",
    # Exceptions
    "SandboxException",
    "SandboxError",
    "SandboxConnectionError",
    "SandboxNotFoundError",
    "SandboxNotRoutableError",
    "SandboxPending",
    "SandboxResizeError",
    "PoolNotFoundError",
    "PoolInUseError",
    "RemoteAPIError",
]
